### ISSUE TITLE
Consider adding phpMyAdmin

### ISSUE THREAD

**Issue by cr101** [10up/wp-local-docker#1]
Please consider adding a phpMyAdmin image and configuration to the docker compose file.

**Comment by tlovett1** [comment]
It's super easy to connect to MySQL using something like Sequel Pro which is much easier to use than phpMyAdmin.

**Comment by cr101** [comment]
Unfortunately Sequel Pro doesn't work on Windows

**Comment by cmmarslender** [comment]
If you would like to add it to your local copy, you can add a `docker-compose.override.yml` file (in the same directory as the `docker-compose.yml` file) with the following in it:
```
version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
```

You'll then be able to access PMA at localhost:8080

the username and password for PMA is then the same that are used with WordPress: 
```
UN: wordpress
PW: password
```
